<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.10" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ValidatedWorld.Application\ValidatedWorld.Application.csproj" />
    <ProjectReference Include="..\ValidatedWorld.Core\ValidatedWorld.Core.csproj" />
    <ProjectReference Include="..\ValidatedWorld.Serialization\ValidatedWorld.Serialization.csproj" />
  </ItemGroup>

</Project>
